services:
  postgres_db:
    image: postgres:16
    container_name: law_firm_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "3002:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: law_firm
    restart: always
    depends_on:
      - postgres_db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      H_USER: ${H_USER}
      H_PASS: ${H_PASS}
    ports:
      - "2002:3000"
    command: ["/bin/sh", "-c", "npx prisma generate && npx prisma migrate deploy && npm run start"]

volumes:
  pg_data: